// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the connected account, surfaced to the frontend.
 */
export type AccountStatus = { connected: boolean, provider: string | null, email: string | null, };
