// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, title: string, start_at: string, end_at: string, location: string | null, description: string | null, attendees: Array<string>, all_day: boolean, };
