// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSource } from "./ChatSource";
import type { ProposedAction } from "./ProposedAction";

export type ChatResponse = { answer: string, sources: Array<ChatSource>, 
/**
 * Action en lot / écrasement proposée par Claude, en attente de
 * confirmation utilisateur (spec/22) — absente pour un tour normal.
 */
pending_action: ProposedAction | null, };
