// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSource } from "./ChatSource";

/**
 * What `ask_notes` returns to the UI: the answer plus the conversation it
 * landed in (freshly created on the first exchange).
 */
export type ChatExchangeResult = { answer: string, sources: Array<ChatSource>, conversation_id: string, };
