// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSource = { 
/**
 * File stem — also the citation key used in [[wikilinks]].
 */
title: string, 
/**
 * Absolute path, for opening the note directly.
 */
path: string, };
