// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAddition } from "./ContextAddition";
import type { TranscriptionFix } from "./TranscriptionFix";
import type { UnassignedTask } from "./UnassignedTask";
import type { UnclearSentence } from "./UnclearSentence";

/**
 * Grouped, thresholded propositions produced by the analysis pass (spec/17 §3).
 */
export type Clarifications = { transcription_fixes: Array<TranscriptionFix>, unassigned_tasks: Array<UnassignedTask>, unclear_sentences: Array<UnclearSentence>, context_additions: Array<ContextAddition>, };
