// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fact learned about the user's world (e.g. "Marie = cheffe de projet") →
 * auto-written to `## Appris automatiquement` (spec/17 §4), non-blocking.
 */
export type ContextAddition = { fact: string, };
