// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fact learned about the user's world (e.g. "Marie = cheffe de projet") →
 * auto-written to `## Appris automatiquement` (spec/17 §4), non-blocking.
 * `scope` (spec/16b §2) sépare le durable non lié à un projet (`"global"` →
 * `Contexte Alfred.md`) du durable propre à un ou plusieurs projets
 * (`"project"` → note(s) de projet, `projects` étant alors un sous-ensemble de
 * `projects_detected`). Défaut `"global"` si absent/mal formé — le critère le
 * plus resserré, jamais un fait perdu dans un projet non voulu.
 */
export type ContextAddition = { fact: string, scope: string, projects: Array<string>, 
/**
 * Section de la note de projet où ranger ce fait (spec/16b — pertinent
 * UNIQUEMENT quand `scope: "project"`, ignoré sinon) : clé interne stable
 * (langue-indépendante, comme les clés de `notes::context::ContextTitles`)
 * — `"overview"|"people"|"decisions"|"events"|"tasks"|"vocabulary"`
 * (`notes::project_context::SECTION_KEYS`). Défaut `"overview"` si
 * absent/invalide — jamais un fait perdu faute de section reconnue.
 */
section: string, };
