// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTodoInput = { title: string, description: string | null, source: string, source_id: string | null, due_date: string | null, };
