// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTodoInput = { title: string, responsable: string | null, echeance: string | null, 
/**
 * Section cible (Kanban « + » par colonne, spec/06). Défaut : « À faire ».
 */
section: string | null, };
