// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une tâche détectée dans un mail (spec/24 §4) — mêmes champs que les tâches
 * d'ingestion (spec/05), sans `project` (porté séparément par `projects` sur
 * l'e-mail entier).
 */
export type EmailTask = { title: string, responsable: string | null, echeance: string | null, };
