// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAddition } from "./ContextAddition";
import type { EmailExtraction } from "./EmailExtraction";

/**
 * Sortie complète d'un batch (spec/24 §4).
 */
export type EmailBatchOutput = { emails: Array<EmailExtraction>, context_additions: Array<ContextAddition>, };
