// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailTask } from "./EmailTask";

/**
 * Sortie par mail (identifié par son `Message-ID`) — absent de la liste si
 * rien d'exploitable (spec/24 §4 : pas de trace pour une newsletter/notif).
 */
export type EmailExtraction = { message_id: string, tasks: Array<EmailTask>, projects: Array<string>, };
