// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNode = { id: string, label: string, kind: string, path: string | null, folder: string | null, };
