// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveChunkEvent = { recording_id: string, seq: number, text: string, start_sec: number, end_sec: number, };
