// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveSessionStarted = { recording_id: string, note_path: string, note_title: string, };
