// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteMetadata } from "./NoteMetadata";

export type LiveSessionSnapshot = { recording_id: string, note_path: string, note_title: string, body: string, metadata: NoteMetadata, last_seq: number, improving: boolean, };
