// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteMetadata = { title: string, date: string, tags: Array<string>, type: string, status: string, recording_id: string | null, 
/**
 * First names of meeting participants, when known (spec/05 ingestion).
 */
participants: Array<string>, 
/**
 * Vault projects this note belongs to (spec/07) — une note peut relever de
 * PLUSIEURS projets (feedback tests) : elle apparaît sous chacun dans la vue
 * Projets. Lecture rétro-compatible avec l'ancienne forme scalaire.
 */
project: Array<string>, };
