// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteMetadata = { title: string, date: string, tags: Array<string>, type: string, status: string, recording_id: string | null, 
/**
 * First names of meeting participants, when known (spec/05 ingestion).
 */
participants: Array<string>, 
/**
 * Vault "project" this note belongs to, when known (spec/07, hors v1 pour le
 * regroupement automatique — le champ existe déjà pour l'ingestion).
 */
project: string | null, };
