// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteMetadata = { title: string, date: string, tags: Array<string>, type: string, status: string, recording_id: string | null, };
