// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteMetadata } from "./NoteMetadata";

export type NoteFile = { path: string, metadata: NoteMetadata, body: string, word_count: number, char_count: number, prop_count: number, };
