// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clarifications } from "./Clarifications";

/**
 * Ce que le front reçoit pour rouvrir `/resolve` SANS relancer `analyze_transcription`
 * (le bouton « Vérifier / corriger » reste le seul chemin qui relance une analyse).
 */
export type PendingClarification = { recording_id: string, note_title: string, text: string, clarifications: Clarifications, summary: boolean, tasks: boolean, };
