// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Item d'un batch de mails en attente de validation (spec/24 §5) — remplace
 * l'écriture directe de l'ancien §4. Exposé au front pour l'écran
 * `/resolve-emails`.
 */
export type PendingEmailReview = { id: bigint, message_id: string, subject: string, email_date: string, 
/**
 * `"task"` | `"context"`.
 */
kind: string, 
/**
 * JSON de `TaskReviewPayload` (kind "task") ou `ContextAddition` (kind
 * "context") — le front désérialise selon `kind` pour l'affichage.
 */
payload: string, status: string, created_at: string, };
