// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhoneCall = { id: string, suggestion_id: string, provider: string, external_call_id: string | null, phone_number: string, party_size: bigint, requested_time: string, status: string, result_summary: string | null, called_at: string | null, completed_at: string | null, };
