// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note plus its `project` frontmatter, for the "group by project" view (spec/07).
 */
export type ProjectNote = { path: string, title: string, 
/**
 * Liste vide → « Sans projet ». Une note peut relever de plusieurs projets
 * (elle apparaît sous chacun — feedback tests, spec/07).
 */
project: Array<string>, type: string, 
/**
 * Lien de paire transcription ↔ compte-rendu (spec/07) : le compte-rendu
 * porte le projet, la transcription est affichée avec lui via ce champ.
 */
recording_id: string | null, };
