// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Une note taguée à ce projet — pas le contenu complet (spec/28 : « liste
 * organisée », pas une synthèse). `date` vient du frontmatter `date`, `None`
 * si vide (fichier créé/édité à la main sans ce champ).
 */
export type ProjectNoteRef = { path: string, title: string, date: string | null, type: string, };
