// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note plus its `project` frontmatter, for the "group by project" view (spec/07).
 */
export type ProjectNote = { path: string, title: string, 
/**
 * `null` → shown under "Sans projet".
 */
project: string | null, type: string, };
