// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarEvent } from "./CalendarEvent";
import type { ContextExcerpt } from "./ContextExcerpt";
import type { ProjectNoteRef } from "./ProjectNoteRef";
import type { Todo } from "./Todo";

export type ProjectOverview = { project: string, context_note: ContextExcerpt | null, open_tasks: Array<Todo>, notes: Array<ProjectNoteRef>, events: Array<CalendarEvent>, };
