// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proposition d'action en attente de confirmation utilisateur — jamais
 * exécutée par la boucle elle-même. `kind` distingue le type de mutation ;
 * seuls les champs pertinents pour ce `kind` sont renseignés.
 */
export type ProposedAction = { kind: string, summary: string, paths: Array<string>, ids: Array<string>, path: string | null, new_body: string | null, };
