// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatSource } from "./ChatSource";

export type StoredChatMessage = { id: string, role: string, content: string, sources: Array<ChatSource> | null, };
