// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Suggestion = { id: string, type: string, calendar_event_id: string | null, payload: string, status: string, created_at: string, };
