// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Édition complète des champs de ligne depuis la fiche tâche (spec/06 2e passe)
 * — `title`/`responsable`/`echeance` + les nouveaux champs inline. La
 * provenance (`source_note`/`source_date`) n'est PAS éditable ici : elle est
 * toujours préservée automatiquement (posée par l'ingestion, jamais par
 * l'utilisateur).
 */
export type TaskFieldsInput = { title: string, responsable: string | null, echeance: string | null, project: string | null, priority: string | null, estimate: string | null, };
