// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Todo = { id: string, title: string, description: string | null, source: string, source_id: string | null, status: string, due_date: string | null, created_at: string, updated_at: string, };
