// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Todo = { 
/**
 * Normalized title — the task's identity in `Todo.md` (no stored ids).
 */
id: string, title: string, responsable: string | null, 
/**
 * YYYY-MM-DD, when present on the line (`📅`).
 */
echeance: string | null, 
/**
 * Which `## Section` the task sits under (Prioritaire / En cours / À faire / Archivé).
 */
section: string, checked: boolean, };
