// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A doubtful passage Claude proposes to correct, with a re-listen anchor. Only
 * emitted when Claude has a referent in the context (spec/17 §3) — never a guess.
 */
export type TranscriptionFix = { 
/**
 * Verbatim doubtful passage from the transcription (the citation).
 */
quote: string, 
/**
 * Proposed corrected text.
 */
correction: string, 
/**
 * 0..1 confidence (thresholding is Claude's; kept for display/sorting).
 */
confidence: number | null, 
/**
 * Re-listen window (seconds), located by matching `quote` to segments.
 */
start: number | null, end: number | null, };
