// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An important but unclear sentence → proposed understanding to confirm.
 */
export type UnclearSentence = { quote: string, proposed: string, start: number | null, end: number | null, };
