// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLink } from "./GraphLink";
import type { GraphNode } from "./GraphNode";

export type VaultGraph = { nodes: Array<GraphNode>, links: Array<GraphLink>, };
