// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultNode = { name: string, path: string, is_dir: boolean, children: Array<VaultNode>, };
