// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultNode = { name: string, path: string, is_dir: boolean, children: Array<VaultNode>, 
/**
 * Frontmatter `status` (spec/07) — `None` for directories. Drives the
 * default hide + dimmed/badge display of archived notes in the tree.
 */
status: string | null, 
/**
 * Frontmatter `recording_id` (spec/07/17) — `None` for directories and
 * notes with no linked recording. Lets the tree cross-reference the
 * pending-clarifications list to show the « à vérifier » indicator.
 */
recording_id: string | null, 
/**
 * Frontmatter `type` (spec/07/16b) — `None` for directories. Drives the
 * context-note icon (`type: context`) in the Dossiers tree, same as the
 * Récents/Projets views (`RecentNote`/`ProjectNote`).
 */
type: string | null, };
