// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VaultNode = { name: string, path: string, is_dir: boolean, children: Array<VaultNode>, 
/**
 * Frontmatter `status` (spec/07) — `None` for directories. Drives the
 * default hide + dimmed/badge display of archived notes in the tree.
 */
status: string | null, };
