// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WhisperModelInfo = { name: string, size_mb: bigint, recommended: boolean, 
/**
 * "downloaded" | "downloading" | "missing"
 */
status: string, active: boolean, };
