// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, source: string, external_id: string, title: string, start_at: string, end_at: string, location: string | null, description: string | null, attendees: string | null, all_day: boolean, last_synced_at: string, };
